In [83]:
import pandas as pd
import numpy as np
data = np.arange(15, 30).reshape(5, 3)
dfx = pd.DataFrame(data, index=['apple', 'banana', 'kiwi',
'grapes', 'mango'], columns=['store1', 'store2', 'store3'])
dfx

        store1  store2  store3
apple       15      16      17
banana      18      19      20
kiwi        21      22      23
grapes      24      25      26
mango       27      28      29

In [84]:
dfx['store4'] = np.nan
dfx.loc['watermelon'] = np.arange(15, 19)
dfx.loc['oranges'] = np.nan
dfx['store5'] = np.nan
dfx['store4']['apple'] = 20.
dfx

/var/folders/mm/xn9dkh0s3qz7t7bzmm4cdp980000gn/T/ipykernel_30276/320494991.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  dfx['store4']['apple'] = 20.

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0     NaN     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN
oranges        NaN     NaN     NaN     NaN     NaN

In [85]:

dfx.isnull()

            store1  store2  store3  store4  store5
apple        False   False   False    True    True
banana       False   False   False    True    True
kiwi         False   False   False    True    True
grapes       False   False   False    True    True
mango        False   False   False    True    True
watermelon   False   False   False   False    True
oranges       True    True    True    True    True

In [86]:
dfx.notnull()

            store1  store2  store3  store4  store5
apple         True    True    True   False   False
banana        True    True    True   False   False
kiwi          True    True    True   False   False
grapes        True    True    True   False   False
mango         True    True    True   False   False
watermelon    True    True    True    True   False
oranges      False   False   False   False   False

In [87]:

dfx.isnull().sum()

store1    1
store2    1
store3    1
store4    6
store5    7
dtype: int64

In [88]:

dfx.isnull().sum().sum()

np.int64(16)

In [89]:

dfx.count()

store1    6
store2    6
store3    6
store4    1
store5    0
dtype: int64

In [90]:
dfx.store4[dfx.store4.notnull()]

watermelon    18.0
Name: store4, dtype: float64

In [91]:

dfx.store4.dropna()

watermelon    18.0
Name: store4, dtype: float64

In [92]:

dfx.dropna()

Empty DataFrame
Columns: [store1, store2, store3, store4, store5]
Index: []

In [93]:

dfx.dropna(how='all')

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0     NaN     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN

In [94]:

dfx.dropna(how='all', axis=1)

            store1  store2  store3  store4
apple         15.0    16.0    17.0     NaN
banana        18.0    19.0    20.0     NaN
kiwi          21.0    22.0    23.0     NaN
grapes        24.0    25.0    26.0     NaN
mango         27.0    28.0    29.0     NaN
watermelon    15.0    16.0    17.0    18.0
oranges        NaN     NaN     NaN     NaN

In [95]:

ar1 = np.array([100, 200, np.nan, 300])
ser1 = pd.Series(ar1)
ar1.mean(), ser1.mean()

(np.float64(nan), np.float64(200.0))

In [96]:
ser2 = dfx.store4
ser2.sum()
#Average
ser2.mean()

np.float64(18.0)

In [97]:

ser2.cumsum()

apple          NaN
banana         NaN
kiwi           NaN
grapes         NaN
mango          NaN
watermelon    18.0
oranges        NaN
Name: store4, dtype: float64

In [98]:

filledDf = dfx.fillna(0)
filledDf

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0     0.0     0.0
banana        18.0    19.0    20.0     0.0     0.0
kiwi          21.0    22.0    23.0     0.0     0.0
grapes        24.0    25.0    26.0     0.0     0.0
mango         27.0    28.0    29.0     0.0     0.0
watermelon    15.0    16.0    17.0    18.0     0.0
oranges        0.0     0.0     0.0     0.0     0.0

In [99]:
dfx.mean()
filledDf.mean()

store1    17.142857
store2    18.000000
store3    18.857143
store4     2.571429
store5     0.000000
dtype: float64

In [100]:
dfx["store4"] = dfx["store4"].ffill()

In [101]:
dfx.store4.bfill()

apple         18.0
banana        18.0
kiwi          18.0
grapes        18.0
mango         18.0
watermelon    18.0
oranges       18.0
Name: store4, dtype: float64